#使うDockerイメージ
FROM mysql:5.7

#ポートを開ける
EXPOSE 3306

# 指定の場所にログを記録するディレクトリを作る
# RUN mkdir /var/log/mysql

# 指定の場所にログを記録するファイルを作る
# RUN touch /var/log/mysql/mysqld.log

#docker runに実行される
CMD ["mysqld"]
